### ISSUE TITLE
ROS first run problems

### ISSUE THREAD

**Issue by mfcarmona** [corb555/iot_bridge#2]
I have detected two minor issues in the iot_bridge ROS wiki page:
1. The sample Open_HAB item definition proposed uses a itemtype (Text) which does not exist. 
I have changed it to String, and it works.
2. The example proposes only one item to be 'exported' to ROS. This makes that instead of a type 'list', iot_bridge parses JSON response as type 'dict', thus failing. (See line 124, variable members).  Avoided this failure adding a second item.

Hope this helps solving it
Regards

**Comment by 130s** [comment]
+1

You're referring to [ROS wiki iot_bridge page](http://wiki.ros.org/iot_bridge) right? You can always edit the page to add improvement.

**Comment by corb555** [comment]
Thanks for the feedback.  I've updated the ROS wiki with this information.  I will close if you confirm that matches your comment above.
