### ISSUE TITLE
Release into ROS?

### ISSUE THREAD

**Issue by 130s** [corb555/iot_bridge#4]
As I mentioned in https://github.com/corb555/iot_bridge/pull/3#issue-235756956, I'm interested in seeing this package released into ROS. "released" means register to their binary package generation process, so that we'll be able to install via `apt-get install`.

@corb555 If this sounds good, I can handle all the release tasks if you want. All I need is a write access to this repository (per each release I'll have to directly commit twice, one for incrementing version in `package.xml`, another for pushing changelog).

Thanks.

**Comment by corb555** [comment]
THat would be great.  I've added you as a collaborator

**Comment by 130s** [comment]
Thank you for your quick response.
Release request is done for:
- ROS Kinetic https://github.com/ros/rosdistro/pull/15267
- ROS Lunar   https://github.com/ros/rosdistro/pull/15268

Would you mind:
- changing the default branch to `kinetic-devel` that I just pushed?
  - ROS developers commonly separate branches per ROS distros, only if necessary when there's change in dependency and/or platform etc.
    - For this package because I don't see so far the necessity between Kinetic and Lunar, both are released using `kinetic-devel`.
  - [This unit test](https://github.com/corb555/iot_bridge/commit/68b96a3fd147f68e95869238e2aa9513d7b42eb8#diff-f1451f158e2370ae2f4b0eca3d2d5e99R10) is currently available only Kinetic onward. And a lot of ROS users have already migrated to this latest LTS (long Term Support) version.
- removing `master` branch accordingly?
  - For ROS distros earlier than Kinetic, I can create branches if there's a need for it.

**Comment by 130s** [comment]
Thank you again for the promptness and for understanding changes (I believe there's no harm in any of the changes I made but hope those are ok..).
